### ISSUE TITLE
Issue importing umbral

### ISSUE THREAD

**Issue by e-lisa** [multiparty/umbral#1]
There is no "umbral" class exported from the package (dist/index.d.ts and dist/service.d.ts)

To reproduce:
npm install umbral
Attempt to include it:
import { umbral } from "umbral";

I noticed there was a "namespace" named CryptoService exported, but no umbral class nor interfaces. To get this to work I am currently cloning this repository to my project to access src/umbral.ts directly.

Thanks & Let me know if you need more info!

**Comment by lucyq** [comment]
sorry about that! I forgot to update the dist folder. I'm adding a few other changes today and will update the package afterwards!
